### ISSUE TITLE
会增加array,arrayvalue,Dictionary属性吗?

### ISSUE THREAD

**Issue by shanyanhai** [chenyunguiMilook/SwiftyXML#1]

**Comment by chenyunguiMilook** [comment]
please provide an example xml, so I can know what you really want ! currently this library supports string, stringValue, int, intValue etc.. to support array, arrayValue, need specify how to convert string to array, that's not common situation~

**Comment by shanyanhai** [comment]
因为我之前是按照json来解析的数据,使用的是swiftyjson,但是后台现在又要给我发xml格式的文件,所以我只是需要一个和swiftyJson一样的库,这样代码里面修改的时候只需要把JSON.init改成XML.init.你这个很接近了,但是还是有点区,或许我需要将xml转成dictionary,这样会牺牲运行效率,但是修改起来方便,而且效率对我的程序并没有太大的用处.还是非常谢谢你

**Comment by chenyunguiMilook** [comment]
you are welcome! by the way, xml have a attributes dictionary you can access directly~
