### ISSUE TITLE
How to access children with hyphen in its name

### ISSUE THREAD

**Issue by garanda21** [chenyunguiMilook/SwiftyXML#18]
My Xml has a lot of values separated by hyphen like "`display-name`" or "`item-id`", but I can't figure ii out on how to access to its values.

If I use the readme instructions like this:

`let name = xml.channel.0.display-name.string` 
`Binary operator '-' cannot be applied to operands of type 'XMLSubscriptResult' and 'String'`

Is there any way to achieve this ?

**Comment by chenyunguiMilook** [comment]
hi, I just did the test, you can try this way: 
print(xml.product[dynamicMember: "catalog_item"].size.color_swatch.1.string)
for you case, should write like: 
let name = xml.channel.0[dynamicMember:"display-name"].string

**Comment by garanda21** [comment]
> let name = xml.channel.0[dynamicMember:"display-name"].string

That did the trick, I also notice that works flawlessly for attributes like:

`xml[dynamicMember: "$info-name"].string`

Thanks for taking the time to reply, I appreciate your effort!

**Comment by chenyunguiMilook** [comment]
You are welcome~
