### ISSUE TITLE
Manual Installation

### ISSUE THREAD

**Issue by lfarah** [chenyunguiMilook/SwiftyXML#3]
```CocoaPods``` and ```Carthage``` are awesome tools and make our life really easier, but there are some devs who still don't know how to use them. 

It would be cool to add the *Manual installation* guide in your ```README.md```. You can take a look at my [iOS Readme Template](https://github.com/awesome-labs/iOS-readme-template) to see how you can do it.

**Comment by lfarah** [comment]
Hey @chenyunguiMilook, thanks for contributing and good job on the library.
I'd ask you to fix this issue before we can approve.
https://github.com/vsouza/awesome-ios/pull/1265

**Comment by chenyunguiMilook** [comment]
thanks lot, I will add it soon~

**Comment by chenyunguiMilook** [comment]
@lfarah I have added CocoaPods and Carthage support !
