### ISSUE TITLE
Characters are removed before first non-ascii character 

### ISSUE THREAD

**Issue by toreboes** [chenyunguiMilook/SwiftyXML#4]
In the attached xml response ([Google geocode response.pdf](https://github.com/chenyunguiMilook/SwiftyXML/files/1029501/Google.geocode.response.pdf), this is the response from url https://maps.googleapis.com/maps/api/geocode/xml?&latlng=63,10), the value of xml["result"][0]["address_component"][3]["short_name"].stringValue is "ør-Trøndelag" (xml is the value of XML(data: data) from the response (using Alamofire)). The correct response should be "Sør-Trøndelag". Thus, the first S is missing. I have also seen other examples where multiple (all) characters before the first non-ascii character is removed in the stringValue.

**Comment by chenyunguiMilook** [comment]
@toreboes Thanks, the issue been fixed!

**Comment by toreboes** [comment]
Hi,

Can you imagine why Cocoapods has version 1.1.0 as the latest version?

There is no way (except copying the code) I can get 1.4.0 in my Xcode Swift project…

regards
Tore


26. mai 2017 kl. 08.22 skrev Kevin <notifications@github.com>:

@toreboes <https://github.com/toreboes> Thanks, the issue been fixed!

**Comment by chenyunguiMilook** [comment]
Hi, 
	Thanks for your notice, I have already push podspec to remote. please use “pod update” to update your pods. 

Best Regards: 
chenyungui
