### ISSUE TITLE
How to make escaping sequence String from xml?

### ISSUE THREAD

**Issue by kiri11ko** [chenyunguiMilook/SwiftyXML#8]
How to make escaping sequence String from XML? For write-in file and send on the server. Thanks.

**Comment by chenyunguiMilook** [comment]
Do you mean to ask this?
https://stackoverflow.com/questions/33860624/escaping-strings-in-swift

**Comment by kiri11ko** [comment]
Yes, I need to check all the value?
Does Library no have the function for this case?

**Comment by kiri11ko** [comment]
How to get all value for the check?

**Comment by chenyunguiMilook** [comment]
Yes, this library will not handle this case, you can escape the whole XML string for you use case~

**Comment by kiri11ko** [comment]
OK. Then do not write what you can create XML as it is not.
I get XML and add new keys to it, but I need to shovel it all to remake special characters since your library returns just a string.

**Comment by kiri11ko** [comment]
For make true XML need in the loop get all value and fix then.
 Example:
         let newXMLHead: XML = XML(name: "clients")
            let usersXML: [XML] = memoryXML!["#clients"]["client"].xmlList!
            for value in usersXML {
                let newXML: XML = XML(name: "clients")
                for (key, subValue) in value.attributes {
                    newXML.addAttribute(name: key, value: subValue.percentEscapeString())
                }
                newXMLHead.addChild(newXML)
            } 

Where 
extension String {
    func percentEscapeString() -> String {
        return self
            .replacingOccurrences(of: "&", with: "\&amp;")
            .replacingOccurrences(of: "\"", with: "\&quot;")
            .replacingOccurrences(of: "'", with: "\&#39;")
            .replacingOccurrences(of: ">", with: "\&gt;")
            .replacingOccurrences(of: "<", with: "\&lt;")
    }
}
