### ISSUE TITLE
For make true XML need in the loop get all value and fix then.

### ISSUE THREAD

**Issue by kiri11ko** [chenyunguiMilook/SwiftyXML#9]
For make true XML need in the loop get all value and fix then.
 Example:
         let newXMLHead: XML = XML(name: "clients")
            let usersXML: [XML] = memoryXML!["#clients"]["client"].xmlList!
            for value in usersXML {
                let newXML: XML = XML(name: "clients")
                for (key, subValue) in value.attributes {
                    newXML.addAttribute(name: key, value: subValue.percentEscapeString())
                }
                newXMLHead.addChild(newXML)
            } 

Where 
extension String {
    func percentEscapeString() -> String {
        return self
            .replacingOccurrences(of: "&", with: "\&amp;")
            .replacingOccurrences(of: "\"", with: "\&quot;")
            .replacingOccurrences(of: "'", with: "\&#39;")
            .replacingOccurrences(of: ">", with: "\&gt;")
            .replacingOccurrences(of: "<", with: "\&lt;")
    }
}

_Originally posted by @kiri11ko in https://github.com/chenyunguiMilook/SwiftyXML/issues/8#issuecomment-511768551_

**Comment by chenyunguiMilook** [comment]
@kiri11ko, thanks for bringing this up, I will schedule to implement this recently.

**Comment by chenyunguiMilook** [comment]
@kiri11ko I have fixed this issue
